/**
 * PDF Export Module — TnT/WTW/Leak Dashboard
 * Uses html2pdf.js (html2canvas + jsPDF) to generate filtered PDF reports.
 * Two export views: Director-level and Sr. Director-level.
 */

/* ── state ── */
let pdfExportTab = 'tnt';

/* ── helpers ── */
function getPeopleForLevel(level) {
    if (level === 'sr_director') {
        return [...new Set(storeData.map(d => d.fm_sr_director_name).filter(Boolean))].sort();
    }
    return [...new Set(storeData.map(d => d.fm_director_name).filter(Boolean))].sort();
}

function getStoresForPerson(level, person) {
    if (level === 'sr_director') {
        return storeData.filter(d => d.fm_sr_director_name === person);
    }
    return storeData.filter(d => d.fm_director_name === person);
}

/* ── modal ── */
function openPdfModal(tab) {
    pdfExportTab = tab;
    const modal = document.getElementById('pdfExportModal');
    modal.classList.remove('hidden');
    document.getElementById('pdfTabLabel').textContent =
        tab === 'tnt' ? 'TnT Dashboard' : tab === 'wtw' ? 'Win the Winter' : 'Leak Management';

    // Default to Sr Director
    document.getElementById('pdfViewLevel').value = 'sr_director';
    updatePdfPersonList();
}

function closePdfModal() {
    document.getElementById('pdfExportModal').classList.add('hidden');
}

function updatePdfPersonList() {
    const level = document.getElementById('pdfViewLevel').value;
    const sel = document.getElementById('pdfPersonSelect');
    const people = getPeopleForLevel(level);
    sel.innerHTML = '<option value="__all__">All (Full Report)</option>' +
        people.map(p => `<option value="${p}">${p}</option>`).join('');
}

/* ── build the capture container ── */
function buildPdfContent(tab, level, person) {
    const isAll = person === '__all__';
    const stores = isAll ? storeData : getStoresForPerson(level, person);
    const levelLabel = level === 'sr_director' ? 'Sr. Director' : 'FM Director';
    const personLabel = isAll ? 'All Regions' : person;
    const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

    const container = document.createElement('div');
    container.style.cssText = 'width:1100px; padding:32px; font-family:system-ui,sans-serif; background:#fff; color:#1a1a1a;';

    // Header
    container.innerHTML = buildPdfHeader(tab, levelLabel, personLabel, dateStr, stores.length);

    if (tab === 'tnt')  container.innerHTML += buildTntPdf(stores, level, person, isAll);
    if (tab === 'wtw')  container.innerHTML += buildWtwPdf(stores, level, person, isAll);
    if (tab === 'leak') container.innerHTML += buildLeakPdf(stores, level, person, isAll);

    // Footer
    container.innerHTML += `
        <div style="margin-top:24px; padding-top:12px; border-top:2px solid #0071ce; font-size:11px; color:#666; display:flex; justify-content:space-between;">
            <span>Generated by TnT Dashboard • ${dateStr}</span>
            <span>${levelLabel}: ${personLabel} • ${stores.length} stores</span>
        </div>`;

    return container;
}

function buildPdfHeader(tab, levelLabel, personLabel, dateStr, storeCount) {
    const tabName = tab === 'tnt' ? '📊 TnT Dashboard' : tab === 'wtw' ? '❄️ Win the Winter' : '🧊 Leak Management';
    return `
        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px; padding-bottom:12px; border-bottom:3px solid #0071ce;">
            <div>
                <h1 style="font-size:22px; font-weight:800; color:#0071ce; margin:0;">${tabName}</h1>
                <p style="font-size:13px; color:#666; margin:4px 0 0;">${levelLabel} Report: ${personLabel}</p>
            </div>
            <div style="text-align:right;">
                <p style="font-size:12px; color:#666; margin:0;">Generated ${dateStr}</p>
                <p style="font-size:12px; color:#666; margin:2px 0 0;">${storeCount} stores</p>
            </div>
        </div>`;
}

/* ── TnT PDF ── */
function buildTntPdf(stores, level, person, isAll) {
    const avgRef = safeAvg(stores, 'twt_ref');
    const avg7d = safeAvg(stores, 'twt_ref_7_day');
    const avg30d = safeAvg(stores, 'twt_ref_30_day');
    const avg90d = safeAvg(stores, 'twt_ref_90_day');
    const avgHvac = safeAvg(stores, 'twt_hvac_30_day');
    const totalLoss = stores.reduce((s, d) => s + (d.total_loss || 0), 0);
    const casesOOT = stores.reduce((s, d) => s + (d.cases_out_of_target || 0), 0);

    let html = `
        <div style="display:grid; grid-template-columns:repeat(5,1fr); gap:12px; margin-bottom:20px;">
            ${kpiBox('Ref TnT (Now)', avgRef, '%')}
            ${kpiBox('Ref 7-Day', avg7d, '%')}
            ${kpiBox('Ref 30-Day', avg30d, '%')}
            ${kpiBox('Ref 90-Day', avg90d, '%')}
            ${kpiBox('HVAC 30-Day', avgHvac, '%')}
        </div>
        <div style="display:grid; grid-template-columns:repeat(3,1fr); gap:12px; margin-bottom:20px;">
            ${kpiBox('Stores', stores.length, '', '#333')}
            ${kpiBox('Total Loss', '$' + totalLoss.toLocaleString(undefined,{maximumFractionDigits:0}), '', '#ea1100')}
            ${kpiBox('Cases OOT', casesOOT.toLocaleString(), '', '#ea1100')}
        </div>`;

    // Group breakdown
    const groupBy = level === 'sr_director' ? 'fm_sr_director_name' : 'fm_director_name';
    const childGroupBy = level === 'sr_director' ? 'fm_director_name' : 'fm_regional_manager_name';
    const childLabel = level === 'sr_director' ? 'Director' : 'Regional Manager';

    // If all, show top-level rollup. If filtered, show children.
    const groups = isAll
        ? groupStores(stores, groupBy)
        : groupStores(stores, childGroupBy);

    html += buildGroupTable(groups, isAll ? (level === 'sr_director' ? 'Sr. Director' : 'Director') : childLabel);

    // Bottom 10 stores
    const bottom10 = [...stores]
        .filter(d => d.twt_ref_30_day !== null)
        .sort((a, b) => (a.twt_ref_30_day || 0) - (b.twt_ref_30_day || 0))
        .slice(0, 10);
    html += `<h3 style="font-size:14px; font-weight:700; margin:20px 0 8px; color:#0071ce;">⚠️ Bottom 10 Stores (Ref 30-Day TnT)</h3>`;
    html += `<table style="width:100%; border-collapse:collapse; font-size:11px;">
        <thead><tr style="background:#0071ce; color:#fff;">
            <th style="${th()}">Store</th><th style="${th()}">Banner</th>
            <th style="${th()}">Market</th><th style="${th()}">RM</th>
            <th style="${th()}">Ref 30d</th><th style="${th()}">HVAC 30d</th>
            <th style="${th()}">Loss</th><th style="${th()}">Cases OOT</th>
        </tr></thead><tbody>`;
    bottom10.forEach((s, i) => {
        const bg = i % 2 === 0 ? '#f9fafb' : '#fff';
        html += `<tr style="background:${bg};">
            <td style="${td()}">${s.store_number}</td>
            <td style="${td()}">${(s.banner_desc||'').includes('Sam') ? 'SAMS' : 'WMT'}</td>
            <td style="${td()}">${s.fs_market || '-'}</td>
            <td style="${td()}">${(s.fm_regional_manager_name || '-').substring(0,20)}</td>
            <td style="${td()} ${scoreColor(s.twt_ref_30_day)}">${pct(s.twt_ref_30_day)}</td>
            <td style="${td()} ${scoreColor(s.twt_hvac_30_day)}">${pct(s.twt_hvac_30_day)}</td>
            <td style="${td()} color:#ea1100;">$${(s.total_loss||0).toLocaleString(undefined,{maximumFractionDigits:0})}</td>
            <td style="${td()}">${(s.cases_out_of_target||0).toLocaleString()}</td>
        </tr>`;
    });
    html += '</tbody></table>';
    return html;
}

/* ── WTW PDF ── */
function buildWtwPdf(stores, level, person, isAll) {
    if (typeof WTW_DATA === 'undefined') return '<p style="color:#999;">No WTW data loaded.</p>';

    const storeNums = new Set(stores.map(s => String(s.store_number)));
    const wtwWos = WTW_DATA.filter(w => storeNums.has(String(w.s)));

    const completed = wtwWos.filter(w => w.st === 'COMPLETED');
    const notCompleted = wtwWos.filter(w => w.st !== 'COMPLETED');
    const p1 = wtwWos.filter(w => w.ph === 'PH1');
    const p2 = wtwWos.filter(w => w.ph === 'PH2');
    const p3 = wtwWos.filter(w => w.ph === 'PH3');
    const avgPm = wtwWos.filter(w => w.pm != null);
    const pmAvg = avgPm.length > 0 ? avgPm.reduce((s,w) => s + parseFloat(w.pm), 0) / avgPm.length : 0;

    let html = `
        <div style="display:grid; grid-template-columns:repeat(5,1fr); gap:12px; margin-bottom:20px;">
            ${kpiBox('Total WOs', wtwWos.length, '', '#333')}
            ${kpiBox('Completed', completed.length, '', '#2a8703')}
            ${kpiBox('Not Completed', notCompleted.length, '', '#ea1100')}
            ${kpiBox('Avg PM Score', pmAvg.toFixed(1), '%')}
            ${kpiBox('Completion %', wtwWos.length > 0 ? ((completed.length/wtwWos.length)*100).toFixed(1) : '0', '%')}
        </div>
        <div style="display:grid; grid-template-columns:repeat(3,1fr); gap:12px; margin-bottom:20px;">
            ${kpiBox('Phase 1', p1.length + ' (' + p1.filter(w=>w.st==='COMPLETED').length + ' done)', '', '#0071ce')}
            ${kpiBox('Phase 2', p2.length + ' (' + p2.filter(w=>w.st==='COMPLETED').length + ' done)', '', '#0071ce')}
            ${kpiBox('Phase 3', p3.length + ' (' + p3.filter(w=>w.st==='COMPLETED').length + ' done)', '', '#0071ce')}
        </div>`;

    // PM Readiness summary
    const ready = wtwWos.filter(w => w.st !== 'COMPLETED' && w.pm != null && parseFloat(w.pm) >= 90);
    const review = wtwWos.filter(w => w.st === 'COMPLETED' && w.pm != null && parseFloat(w.pm) >= 90);
    const critical = wtwWos.filter(w => w.st === 'COMPLETED' && w.pm != null && parseFloat(w.pm) < 90);

    html += `
        <h3 style="font-size:14px; font-weight:700; margin:16px 0 8px; color:#0071ce;">🎯 PM Readiness Summary</h3>
        <div style="display:grid; grid-template-columns:repeat(3,1fr); gap:12px; margin-bottom:20px;">
            ${kpiBox('✓ Ready to Complete', ready.length, '', '#2a8703')}
            ${kpiBox('🔍 Review Needed', review.length, '', '#f59e0b')}
            ${kpiBox('⚠ Critical Reopen', critical.length, '', '#ea1100')}
        </div>`;

    // Top not-completed WOs
    const topOpen = notCompleted.slice(0, 15);
    if (topOpen.length > 0) {
        html += `<h3 style="font-size:14px; font-weight:700; margin:16px 0 8px; color:#0071ce;">📋 Top Open WTW Work Orders (by age)</h3>`;
        html += `<table style="width:100%; border-collapse:collapse; font-size:11px;">
            <thead><tr style="background:#0071ce; color:#fff;">
                <th style="${th()}">Store</th><th style="${th()}">Tracking #</th>
                <th style="${th()}">Phase</th><th style="${th()}">PM Score</th>
                <th style="${th()}">Status</th>
            </tr></thead><tbody>`;
        topOpen.forEach((w, i) => {
            const bg = i % 2 === 0 ? '#f9fafb' : '#fff';
            const pm = w.pm != null ? parseFloat(w.pm).toFixed(0) + '%' : 'N/A';
            html += `<tr style="background:${bg};">
                <td style="${td()}">${w.s}</td>
                <td style="${td()}">${w.t}</td>
                <td style="${td()}">Phase ${(w.ph || '?').replace('PH','')}</td>
                <td style="${td()} ${scoreColor(w.pm ? parseFloat(w.pm) : null)}">${pm}</td>
                <td style="${td()}">${w.st}</td>
            </tr>`;
        });
        html += '</tbody></table>';
    }

    // Group breakdown for WTW by director/RM
    const childGroupBy = level === 'sr_director' ? 'fm' : 'rm';
    const childLabel = level === 'sr_director' ? 'Director' : 'Regional Manager';
    const grpMap = {};
    wtwWos.forEach(w => {
        const grp = w[childGroupBy] || 'Unknown';
        if (!grpMap[grp]) grpMap[grp] = { total: 0, completed: 0, pmSum: 0, pmCount: 0 };
        grpMap[grp].total++;
        if (w.st === 'COMPLETED') grpMap[grp].completed++;
        if (w.pm != null) { grpMap[grp].pmSum += parseFloat(w.pm); grpMap[grp].pmCount++; }
    });
    const wtwGroups = Object.entries(grpMap)
        .map(([name, d]) => ({ name, ...d, pct: d.total > 0 ? (d.completed/d.total*100) : 0, pmAvg: d.pmCount > 0 ? d.pmSum/d.pmCount : 0 }))
        .sort((a,b) => a.pct - b.pct);

    if (wtwGroups.length > 1) {
        html += `<h3 style="font-size:14px; font-weight:700; margin:20px 0 8px; color:#0071ce;">📊 WTW Completion by ${childLabel}</h3>`;
        html += `<table style="width:100%; border-collapse:collapse; font-size:11px;">
            <thead><tr style="background:#0071ce; color:#fff;">
                <th style="${th()}">${childLabel}</th><th style="${th()}">Total</th>
                <th style="${th()}">Completed</th><th style="${th()}">Completion %</th>
                <th style="${th()}">Avg PM</th>
            </tr></thead><tbody>`;
        wtwGroups.forEach((g, i) => {
            const bg = i % 2 === 0 ? '#f9fafb' : '#fff';
            html += `<tr style="background:${bg};">
                <td style="${td()} font-weight:600;">${g.name}</td>
                <td style="${td()}">${g.total}</td>
                <td style="${td()}">${g.completed}</td>
                <td style="${td()} ${scoreColor(g.pct)}">${g.pct.toFixed(1)}%</td>
                <td style="${td()} ${scoreColor(g.pmAvg)}">${g.pmAvg.toFixed(1)}%</td>
            </tr>`;
        });
        html += '</tbody></table>';
    }

    return html;
}

/* ── Leak PDF ── */
function buildLeakPdf(stores, level, person, isAll) {
    if (typeof LK_STORES === 'undefined') return '<p style="color:#999;">No leak data loaded.</p>';

    const storeNums = new Set(stores.map(s => String(s.store_number)));
    const leakStores = LK_STORES.filter(s => storeNums.has(String(s.s)));
    const totalCharge = leakStores.reduce((s,d) => s + (d.sc || 0), 0);
    const totalQty = leakStores.reduce((s,d) => s + (d.cytq || 0), 0);
    const totalLeaks = leakStores.reduce((s,d) => s + (d.cyl || 0), 0);
    const avgRate = totalCharge > 0 ? (totalQty / totalCharge * 100) : 0;
    const LK_T_VAL = typeof LK_T !== 'undefined' ? LK_T : 20;
    const overThreshold = leakStores.filter(s => s.cylr > LK_T_VAL).length;

    let html = `
        <div style="display:grid; grid-template-columns:repeat(5,1fr); gap:12px; margin-bottom:20px;">
            ${kpiBox('Stores', leakStores.length, '', '#333')}
            ${kpiBox('Total Charge (lbs)', totalCharge.toLocaleString(undefined,{maximumFractionDigits:0}), '', '#333')}
            ${kpiBox('Leaked (lbs)', totalQty.toLocaleString(undefined,{maximumFractionDigits:0}), '', '#ea1100')}
            ${kpiBox('Avg Leak Rate', avgRate.toFixed(1), '%')}
            ${kpiBox('Over ' + LK_T_VAL + '%', overThreshold, '', '#ea1100')}
        </div>`;

    // Top leaking stores
    const top15 = [...leakStores]
        .sort((a,b) => (b.cylr || 0) - (a.cylr || 0))
        .slice(0, 15);

    html += `<h3 style="font-size:14px; font-weight:700; margin:16px 0 8px; color:#0071ce;">🚨 Top Leaking Stores</h3>`;
    html += `<table style="width:100%; border-collapse:collapse; font-size:11px;">
        <thead><tr style="background:#0071ce; color:#fff;">
            <th style="${th()}">Store</th><th style="${th()}">City</th>
            <th style="${th()}">Banner</th><th style="${th()}">Charge (lbs)</th>
            <th style="${th()}">Leaked (lbs)</th><th style="${th()}">Leak Rate</th>
            <th style="${th()}">Leak Count</th><th style="${th()}">Status</th>
        </tr></thead><tbody>`;
    top15.forEach((s, i) => {
        const bg = i % 2 === 0 ? '#f9fafb' : '#fff';
        const rateColor = s.cylr > LK_T_VAL ? 'color:#ea1100; font-weight:700;' : s.cylr > LK_T_VAL * 0.7 ? 'color:#f59e0b;' : 'color:#2a8703;';
        const icon = s.cylr > LK_T_VAL * 1.5 ? '🚨' : s.cylr > LK_T_VAL ? '⚠️' : '✅';
        html += `<tr style="background:${bg};">
            <td style="${td()}">${s.s}</td>
            <td style="${td()}">${s.city || ''}${s.city && s.st ? ', ' : ''}${s.st || ''}</td>
            <td style="${td()}">${(s.ban||'').includes('Sam') ? 'SAMS' : 'WMT'}</td>
            <td style="${td()}">${Math.round(s.sc).toLocaleString()}</td>
            <td style="${td()} color:#ea1100;">${Math.round(s.cytq).toLocaleString()}</td>
            <td style="${td()} ${rateColor}">${s.cylr.toFixed(1)}%</td>
            <td style="${td()}">${s.cyl}</td>
            <td style="${td()}">${icon}</td>
        </tr>`;
    });
    html += '</tbody></table>';

    // Group summary by RM or Director — leak data has srd/fm/rm directly
    const leakGroupKey = level === 'sr_director' ? 'fm' : 'rm';
    const childLabel = level === 'sr_director' ? 'Director' : 'Regional Manager';

    const groupMap = {};
    leakStores.forEach(ls => {
        const grp = ls[leakGroupKey] || 'Unknown';
        if (!groupMap[grp]) groupMap[grp] = { charge: 0, qty: 0, leaks: 0, stores: 0, over: 0 };
        groupMap[grp].charge += ls.sc || 0;
        groupMap[grp].qty += ls.cytq || 0;
        groupMap[grp].leaks += ls.cyl || 0;
        groupMap[grp].stores++;
        if (ls.cylr > LK_T_VAL) groupMap[grp].over++;
    });

    const groups = Object.entries(groupMap)
        .map(([name, d]) => ({ name, ...d, rate: d.charge > 0 ? (d.qty / d.charge * 100) : 0 }))
        .sort((a, b) => b.rate - a.rate);

    if (groups.length > 1) {
        html += `<h3 style="font-size:14px; font-weight:700; margin:20px 0 8px; color:#0071ce;">📊 Leak Rate by ${childLabel}</h3>`;
        html += `<table style="width:100%; border-collapse:collapse; font-size:11px;">
            <thead><tr style="background:#0071ce; color:#fff;">
                <th style="${th()}">${childLabel}</th><th style="${th()}">Stores</th>
                <th style="${th()}">Charge</th><th style="${th()}">Leaked</th>
                <th style="${th()}">Leak Rate</th><th style="${th()}">Over ${LK_T_VAL}%</th>
            </tr></thead><tbody>`;
        groups.forEach((g, i) => {
            const bg = i % 2 === 0 ? '#f9fafb' : '#fff';
            const rateColor = g.rate > LK_T_VAL ? 'color:#ea1100; font-weight:700;' : 'color:#2a8703;';
            html += `<tr style="background:${bg};">
                <td style="${td()} font-weight:600;">${g.name}</td>
                <td style="${td()}">${g.stores}</td>
                <td style="${td()}">${Math.round(g.charge).toLocaleString()}</td>
                <td style="${td()}">${Math.round(g.qty).toLocaleString()}</td>
                <td style="${td()} ${rateColor}">${g.rate.toFixed(1)}%</td>
                <td style="${td()} ${g.over > 0 ? 'color:#ea1100;' : ''}">${g.over}</td>
            </tr>`;
        });
        html += '</tbody></table>';
    }

    // Group breakdown for WTW by director/RM
    const childGroupBy = level === 'sr_director' ? 'fm' : 'rm';
    const childLabel = level === 'sr_director' ? 'Director' : 'Regional Manager';
    const grpMap = {};
    wtwWos.forEach(w => {
        const grp = w[childGroupBy] || 'Unknown';
        if (!grpMap[grp]) grpMap[grp] = { total: 0, completed: 0, pmSum: 0, pmCount: 0 };
        grpMap[grp].total++;
        if (w.st === 'COMPLETED') grpMap[grp].completed++;
        if (w.pm != null) { grpMap[grp].pmSum += parseFloat(w.pm); grpMap[grp].pmCount++; }
    });
    const wtwGroups = Object.entries(grpMap)
        .map(([name, d]) => ({ name, ...d, pct: d.total > 0 ? (d.completed/d.total*100) : 0, pmAvg: d.pmCount > 0 ? d.pmSum/d.pmCount : 0 }))
        .sort((a,b) => a.pct - b.pct);

    if (wtwGroups.length > 1) {
        html += `<h3 style="font-size:14px; font-weight:700; margin:20px 0 8px; color:#0071ce;">📊 WTW Completion by ${childLabel}</h3>`;
        html += `<table style="width:100%; border-collapse:collapse; font-size:11px;">
            <thead><tr style="background:#0071ce; color:#fff;">
                <th style="${th()}">${childLabel}</th><th style="${th()}">Total</th>
                <th style="${th()}">Completed</th><th style="${th()}">Completion %</th>
                <th style="${th()}">Avg PM</th>
            </tr></thead><tbody>`;
        wtwGroups.forEach((g, i) => {
            const bg = i % 2 === 0 ? '#f9fafb' : '#fff';
            html += `<tr style="background:${bg};">
                <td style="${td()} font-weight:600;">${g.name}</td>
                <td style="${td()}">${g.total}</td>
                <td style="${td()}">${g.completed}</td>
                <td style="${td()} ${scoreColor(g.pct)}">${g.pct.toFixed(1)}%</td>
                <td style="${td()} ${scoreColor(g.pmAvg)}">${g.pmAvg.toFixed(1)}%</td>
            </tr>`;
        });
        html += '</tbody></table>';
    }

    return html;
}

/* ── shared helpers ── */
function safeAvg(data, field) {
    const valid = data.filter(d => d[field] !== null && d[field] !== undefined && !isNaN(d[field]));
    return valid.length ? valid.reduce((s, d) => s + d[field], 0) / valid.length : 0;
}

function groupStores(stores, groupBy) {
    const map = {};
    stores.forEach(s => {
        const key = s[groupBy] || 'Unknown';
        if (!map[key]) map[key] = [];
        map[key].push(s);
    });
    return Object.entries(map)
        .map(([name, ss]) => ({
            name,
            count: ss.length,
            avgRef30: safeAvg(ss, 'twt_ref_30_day'),
            avgHvac30: safeAvg(ss, 'twt_hvac_30_day'),
            totalLoss: ss.reduce((s, d) => s + (d.total_loss || 0), 0),
            casesOOT: ss.reduce((s, d) => s + (d.cases_out_of_target || 0), 0),
        }))
        .sort((a, b) => a.avgRef30 - b.avgRef30);
}

function buildGroupTable(groups, label) {
    let html = `<h3 style="font-size:14px; font-weight:700; margin:16px 0 8px; color:#0071ce;">📊 Performance by ${label}</h3>`;
    html += `<table style="width:100%; border-collapse:collapse; font-size:11px;">
        <thead><tr style="background:#0071ce; color:#fff;">
            <th style="${th()}">${label}</th><th style="${th()}">Stores</th>
            <th style="${th()}">Ref 30d</th><th style="${th()}">HVAC 30d</th>
            <th style="${th()}">Total Loss</th><th style="${th()}">Cases OOT</th>
        </tr></thead><tbody>`;
    groups.forEach((g, i) => {
        const bg = i % 2 === 0 ? '#f9fafb' : '#fff';
        html += `<tr style="background:${bg};">
            <td style="${td()} font-weight:600;">${g.name}</td>
            <td style="${td()}">${g.count}</td>
            <td style="${td()} ${scoreColor(g.avgRef30)}">${g.avgRef30.toFixed(1)}%</td>
            <td style="${td()} ${scoreColor(g.avgHvac30)}">${g.avgHvac30.toFixed(1)}%</td>
            <td style="${td()} color:#ea1100;">$${g.totalLoss.toLocaleString(undefined,{maximumFractionDigits:0})}</td>
            <td style="${td()}">${g.casesOOT.toLocaleString()}</td>
        </tr>`;
    });
    html += '</tbody></table>';
    return html;
}

function kpiBox(label, value, suffix, color) {
    const c = color || (parseFloat(value) >= 90 ? '#2a8703' : parseFloat(value) >= 80 ? '#f59e0b' : '#ea1100');
    const displayVal = typeof value === 'number' ? value.toFixed(1) : value;
    return `
        <div style="border:1px solid #e5e7eb; border-radius:8px; padding:12px; text-align:center; background:#fafafa;">
            <div style="font-size:22px; font-weight:800; color:${c};">${displayVal}${suffix || ''}</div>
            <div style="font-size:11px; color:#666; margin-top:4px;">${label}</div>
        </div>`;
}

function th() { return 'padding:6px 8px; text-align:left; font-size:11px; font-weight:600;'; }
function td() { return 'padding:5px 8px; border-bottom:1px solid #e5e7eb;'; }
function pct(v) { return v !== null && v !== undefined ? v.toFixed(1) + '%' : 'N/A'; }

function scoreColor(v) {
    if (v === null || v === undefined) return 'color:#999;';
    if (v >= 90) return 'color:#2a8703; font-weight:700;';
    if (v >= 80) return 'color:#f59e0b; font-weight:600;';
    return 'color:#ea1100; font-weight:700;';
}

/* ── generate PDF ── */
async function generatePdf() {
    const level = document.getElementById('pdfViewLevel').value;
    const person = document.getElementById('pdfPersonSelect').value;
    const btn = document.getElementById('pdfGenerateBtn');

    btn.disabled = true;
    btn.textContent = '⏳ Generating...';

    try {
        const content = buildPdfContent(pdfExportTab, level, person);

        // Temporarily append to DOM for html2pdf to render
        content.style.position = 'fixed';
        content.style.left = '-9999px';
        content.style.top = '0';
        document.body.appendChild(content);

        const levelSlug = level === 'sr_director' ? 'SrDir' : 'Dir';
        const personSlug = person === '__all__' ? 'All' : person.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 20);
        const tabSlug = pdfExportTab.toUpperCase();
        const dateSlug = new Date().toISOString().slice(0, 10);
        const filename = `${tabSlug}_${levelSlug}_${personSlug}_${dateSlug}.pdf`;

        const opt = {
            margin:       [0.3, 0.3, 0.3, 0.3],
            filename:     filename,
            image:        { type: 'jpeg', quality: 0.95 },
            html2canvas:  { scale: 2, useCORS: true, logging: false, width: 1100 },
            jsPDF:        { unit: 'in', format: 'letter', orientation: 'landscape' },
            pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
        };

        await html2pdf().set(opt).from(content).save();
        document.body.removeChild(content);
        closePdfModal();
    } catch (err) {
        console.error('PDF generation failed:', err);
        alert('PDF generation failed: ' + err.message);
    } finally {
        btn.disabled = false;
        btn.textContent = '📄 Generate PDF';
    }
}
